POST http://localhost:3001/login
Content-Type:application/json

{
  "email":"huyhoang10032000@gmail.com",
  "password":"huyhoang"
}

###

GET http://localhost:3001/admin/getPendingPromotion
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1eWhvYW5nMTAwMzIwMDBAZ21haWwuY29tIiwiaWQiOjEsInBlcm1pc3Npb24iOiJDT19BRE1JTiIsInRva2VuRXhwaXJlVGltZSI6MTYyMzkzOTg0MzQ4MiwiaWF0IjoxNjIzOTM2MjQzLCJleHAiOjE2MjM5Mzk4NDN9.G_0NRv_ltQKfjR7tWx_XrcIOnns_8VkrO8PGNfsAetc


###
POST http://localhost:3001/refresh_token
Content-Type:application/json

{
  "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnB1dCI6eyJlbWFpbCI6Imh1eWhvYW5nMTAwMzIwMDBAZ21haWwuY29tIn0sInJlZnJlc3RUb2tlbkV4cGlyZVRpbWUiOjE2MjA0Nzk1MjA5MjYsImlhdCI6MTYyMDM5MzEyMCwiZXhwIjoxNjIwNDc5NTIwfQ.F9GE53fJBOMJsM1S_xBI_5593ypRYhpbIY_a4"
}

###

GET http://localhost:3001/hh
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1eWhvYW5nMTAwMzIwMDBAZ21haWwuY29tIiwiaWQiOjEwMDAsInRva2VuRXhwaXJlVGltZSI6MTYyMDUwNjg5NjY5MSwiaWF0IjoxNjIwNTAzMjk2LCJleHAiOjE2MjA1MDY4OTZ9.dCsIB1rGIqsNzSSA3NuyfP-2JBeORcoMUwVH8HTdXYI

###

GET http://localhost:3001/room/currentRoom/hadadadadadaadada

###

GET http://localhost:3001/room/getPendingRoom?name=h
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1eWhvYW5nMTAwMzIwMDBAZ21haWwuY29tIiwiaWQiOjEsInBlcm1pc3Npb24iOiJDT19BRE1JTiIsInRva2VuRXhwaXJlVGltZSI6MTYyMzc3MDcyODgxNCwiaWF0IjoxNjIzNzY3MTI4LCJleHAiOjE2MjM3NzA3Mjh9.00seLe_mAsVO7qp3xTgQs9HGHnrC8zlJYT5Gw9H4TFo
###

POST http://localhost:3001/admin/rejectRoom
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1eWhvYW5nMTAwMzIwMDBAZ21haWwuY29tIiwiaWQiOjEsInBlcm1pc3Npb24iOiJDT19BRE1JTiIsInRva2VuRXhwaXJlVGltZSI6MTYyMzc3MDcyODgxNCwiaWF0IjoxNjIzNzY3MTI4LCJleHAiOjE2MjM3NzA3Mjh9.00seLe_mAsVO7qp3xTgQs9HGHnrC8zlJYT5Gw9H4TFo

{
  "id_room":92
}
###



GET http://localhost:3001/user/1


{
  "email":"huyhoang10032000@gmail.com",
  "password":"1234567",
  "user_name":"bhuy"
}
